2019-12-14 23:22:29,640 ERROR: Exception on /contact [GET] [in c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kusuma Mulpuru\microblog\app\routes.py", line 203, in contact
    return render_template('contact.html', form=form)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 14, in root
    <p>
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\base.html", line 14, in root
    <span class="icon-bar"></span>
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 35, in block_content
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'app.forms.ContactForm object' has no attribute 'contactkInfo'
2019-12-14 23:22:47,465 ERROR: Exception on /contact [GET] [in c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kusuma Mulpuru\microblog\app\routes.py", line 203, in contact
    return render_template('contact.html', form=form)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 14, in root
    <p>
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\base.html", line 14, in root
    <span class="icon-bar"></span>
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\kusuma Mulpuru\microblog\app\templates\contact.html", line 35, in block_content
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\kusuma mulpuru\microblog\venv\lib\site-packages\jinja2\runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'app.forms.ContactForm object' has no attribute 'contactkInfo'
2019-12-14 23:27:52,834 INFO: Microblog startup [in C:\Users\kusuma Mulpuru\microblog\app\__init__.py:49]
